// V0928a
var pageData = {};
pageData.blog_data = [
    {"new":1,"title":"DE&I Hiring Data: Top Locations, Market Values, and Industry Experience","img":"https://hiretual.com/wp-content/uploads/2021/10/Website-Blog-Header-27-1080x675.png","url":"/blog/dei-report-2021","content":"Talent professionals have probably said these three words more than “I love you”....","read_time":"3 min","classify":["Recruiting Strategy","Data & Metrics","Talent Sourcing","Diversity & Inclusion"]},
    {"new":1,"title":"Struggling to Hire Military Veterans? 4 Strategies to Follow","img":"https://hiretual.com/wp-content/uploads/2021/10/Website-Blog-Header-26-1080x675.png","url":"/blog/hire-military-veterans","content":"In today’s post-pandemic talent market, there are...","read_time":"7 min","classify":["Recruiting Strategy","Candidate Engagement","Talent Sourcing","Diversity & Inclusion"]},
    {"new":1,"title":"Hiretual at HRTech 2021: Can you have fun finding talent?","img":"https://hiretual.com/wp-content/uploads/2021/10/HR-Tech-1080x675.png","url":"/blog/fun-finding-talent-hrtech-2021/","content":"A few weeks ago, Hiretual was so pumped to attend our...","read_time":"2 min","classify":["Events"]},

    {"title":"How Hiring Bias Is Slowing Down Your DE&I Recruitment Efforts","img":"https://hiretual.com/wp-content/uploads/2021/09/Website-Blog-Header-8-1080x675.png","url":"/blog/reduce-hiring-bias","content":"If you clicked in hoping to prevent hiring bias in your ...","read_time":"7 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"What’s the Big Deal About Hiretual? Everything You Might Not Know","img":"https://hiretual.com/wp-content/uploads/2021/09/unit-head1.png","url":"/blog/everything-you-might-not-know-about-hiretual/","content":"Like most Talent Acquisition teams out there...","read_time":"11 min","classify":["Diversity & Inclusion"]},
    {"title":"How much do recruiters make? What we learned from 250+ responses","img":"https://hiretual.com/wp-content/uploads/2021/09/Demand-for-TA-report-header-1080x675.png","url":"/blog/how-much-do-recruiters-make/","content":"Throughout the year, Hiretual has released reports digging into recruiter...","read_time":"3 min","classify":["Recruitment Operations","Data & Metrics"]},
    {"title":"Hiretual at SHRM 2021: Helping HR build the new workplace of today","img":"https://hiretual.com/wp-content/uploads/2021/09/Website-Blog-Header-6-1080x675.png","url":"/blog/shrm-conference-2021-recap/","content":"If you’ve been following Hiretual over the past few years....","read_time":"4 min","classify":["Recruiting Strategy","Events"]},
    {"title":"5 Healthcare Recruiting Tips for Uncovering Talent with Data Intelligence","img":"https://hiretual.com/wp-content/uploads/2021/05/Website-Blog-Header-1-1080x675.png","url":"/blog/5-healthcare-recruiting-tips-to-help-you-uncover-talent-with-data-intelligence/","content":"A global health crisis exerts immense stress on limited healthcare... ","read_time":"5 min","classify":["Talent Sourcing","Recruiting Strategy","Candidate Engagement","Data & Metrics","Diversity & Inclusion"]},
    {"title":"The Most Strategic Interview Question to Find Successful Candidates","img":"https://hiretual.com/wp-content/uploads/2021/09/Lou-Adler-Post-Webinar-Blog-Header-1080x675.png","url":"/blog/strategic-interview-questions-to-ask-candidates/","content":"Imagine trying to interview hundreds of people at the same time... ","read_time":"5 min","classify":["Recruiting Strategy","Candidate Engagement"]},
    {"title":"Losing Talent to a Poor Candidate Experience? 4 Changes to Make Today","img":"https://hiretual.com/wp-content/uploads/2021/09/Codility-Blog-Webinar-Header-1080x675.png","url":"/blog/create-a-positive-candidate-experience/","content":"Many of us have thought about balance in the past year...","read_time":"6 min","classify":["Recruiting Strategy","Candidate Engagement"]},
    {"title":"How Hard Is It to Find and Hire Software Engineers? We Have the Data","img":"https://hiretual.com/wp-content/uploads/2021/09/software-engineer-1080x675.png","url":"/blog/hire-software-engineer/","content":"Do you know that feeling when you’re looking through your...","read_time":"3 min","classify":["Recruiting Strategy","Talent Sourcing","Data & Metrics"]},
    {"title":"Collaborative Hiring Gone Wrong? Here’s What Hiretual Can Do","img":"https://hiretual.com/wp-content/uploads/2021/08/collaboration-guide-1080x675.png","url":"/blog/collaborative-recruiting-and-hiring/","content":"Does collaborative hiring ever feel like a horror movie?","read_time":"6 min","classify":["Recruiting Strategy","Product","Team Collaboration"]},
    {"title":"High-Volume Hiring Guide: Talent Experience, Turnover, and Transparency","img":"https://hiretual.com/wp-content/uploads/2021/08/high-volume-hiring-1080x675.png","url":"/blog/high-volume-hiring-strategies/","content":"Normally, we would start off our checklist with a metaphor or meaningful quote...","read_time":"6 min","classify":["Recruiting Strategy","Talent Sourcing","Candidate Engagement","Diversity & Inclusion"]},
    {"title":"Hiring Remote Workers: 3 Guidelines Companies Should Follow","img":"https://hiretual.com/wp-content/uploads/2021/08/Website-Blog-Header-21-1080x675.png","url":"/blog/how-to-hire-remote-worker/","content":"“Where do you see yourself in 5 years?” It’s an age-old question asked of interviewees...","read_time":"6 min","classify":["Recruiting Strategy","Talent Sourcing","Diversity & Inclusion"]},
    {"title":"What is Hiretual’s Talent Data Cloud (& Why Our Customers Use It)","img":"https://hiretual.com/wp-content/uploads/2021/07/Website-Blog-Header-20-1080x675.png","url":"/blog/what-is-hiretual-talent-data-cloud/","content":"Across the country, we’re facing a shortage of these items....","read_time":"6 min","classify":["Product","Talent Sourcing","Team Collaboration"]},
    {"title":"Behind the Stats: Breaking Down Our Recruiting for Recovery Report","img":"https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/07/videoimg.png","url":"/recruiting-for-recovery/","content":"Q&A with Glenn Gutmacher, Director of Talent Sourcing at Huron Consulting Group....","read_time":"1 min","classify":["Recruiting Strategy"]},
    {"title":"How Recruitment Analytics Will Change the Workplace As We Know It","img":"https://hiretual.com/wp-content/uploads/2021/07/Website-Blog-Header-16-1080x675.png","url":"/blog/recruitment-analytics-in-workplace/","content":"When it comes to businesses understanding consumer behavior, data is key...","read_time":"6 min","classify":["Data & Metrics","Recruiting Strategy"]},
    {"title":"Why 65% of Hiring Teams Source Talent From Their ATS","img":"https://hiretual.com/wp-content/uploads/2021/07/65-ATS-1080x675.png","url":"/blog/ats-talent-rediscovery-improve-recruitment/","content":"By now, your team may have already started its post-pandemic hiring efforts...","read_time":"5 min","classify":["Talent Sourcing","Recruiting Strategy","Product"]},
    {"title":"3 Reasons Why Your Company Should Not Adopt AI Recruitment Technology","img":"https://hiretual.com/wp-content/uploads/2021/07/3-Reasons-Blog-Header-1080x675.png","url":"/blog/recruitment-technology-adoption/","content":"Are you a recruiter on the fence about adopting an AI recruitment tool...","read_time":"7 min","classify":["Talent Sourcing","Product"]},
    {"title":"4 Ways to Prepare for Hiring in Market Recovery (According to Data)","img":"https://hiretual.com/wp-content/uploads/2021/07/Website-Blog-Header-13-1080x675.png","url":"/blog/hiring-surge-in-market-recovery/","content":"Employer competition during hiring surges. Unemployment benefits influencin...","read_time":"8 min","classify":["Talent Sourcing","Candidate Engagement","Recruiting Strategy","Data & Metrics"]},
    {"title":"Users Love Hiretual on G2 (and We Have the Awards to Prove It)","img":"https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/07/G2-Blog-Header-1080x675.png","url":"/blog/g2-award-recruiting-automation-software/","content":"When a company wins a product award, the product and its creators usually get…","read_time":"4 min","classify":["Product"]},
    {"title":"How to Pick Your Next Recruitment Technology: 10 Questions to Ask","img":"https://hiretual.com/wp-content/uploads/2021/06/Website-Blog-Header-14-1080x675.png","url":"/blog/recruitment-technology-guide/","content":"As we leave behind a year full of uncertainty, recruiters are ready for answers…","read_time":"11 min","classify":["Recruiting Strategy","Diversity & Inclusion"]},
    {"title":"Small Business Hiring: Affordable, Flexible, and Scalable Technology","img":"https://hiretual.com/wp-content/uploads/2021/06/smb-blog-1080x675.png","url":"/blog/small-business-hiring/","content":"“Technology can only level the playing field when everyone has equal access to it…","read_time":"6 min","classify":["Recruiting Strategy","Talent Sourcing","Candidate Engagement"]},
    {"title":"A New Look, a Bigger Mission, and a Better Hiretual","img":"https://hiretual.com/wp-content/uploads/2021/06/blog_header_new_hiretual_website-1080x675.png","url":"/blog/new-hiretual-website/","content":"If you know Hiretual as an AI-powered candidate sourcing platform, we’re here to say…","read_time":"2 min","classify":["Product"]},
    {"title":"5 Proven Steps Every Diversity Hiring Process Needs","img":"https://hiretual.com/wp-content/uploads/2021/06/revised-header-for-diversity-hiring-blog-1080x675.png","url":"/blog/diversity-hiring-process-tips/","content":"By now, you’ve already heard about the importance of workplace...","read_time":"7 min","classify":["Recruiting Strategy","Talent Sourcing","Diversity & Inclusion"]},
    {"title":"Why Recruiting Automation Doesn’t Have to Be Boring","img":"https://hiretual.com/wp-content/uploads/2021/05/Beyond-Recruiting-Automation-Header-1080x675.png","url":"/blog/go-beyond-boring-recruiting-automation/","content":"From self-driving cars to cancer detection tools, automation has made...","read_time":"9 min","classify":["Candidate Engagement","Talent Sourcing","Recruiting Strategy","Diversity & Inclusion"]},
    {"title":"10 Powerful Recruiting Tools For Modern Recruitment Teams","img":"https://hiretual.com/wp-content/uploads/2021/05/Modern-Recruitment-Team-10-Tools-Blog-1080x675.png","url":"/blog/top-recruiting-tools/","content":"We have some good news and some bad news for modern recruitment teams...","read_time":"6 min","classify":["Talent Sourcing","Diversity & Inclusion"]},
    {"title":"The 4C’s of Recruitment Operations: Designing A Problem-Solving Process","img":"https://hiretual.com/wp-content/uploads/2021/05/Recruitment-Ops-Blog-Header-1080x675.png","url":"/blog/recruitment-operations-process/","content":"If you haven’t already noticed, Talent Acquisition is vaguely defined...","read_time":"8 min","classify":["Recruitment Operations"]},
    {"title":"How To Recruit Candidates with Published Journals and Patents","img":"https://hiretual.com/wp-content/uploads/2021/05/Website-Blog-Header-copy-1080x675.png","url":"/blog/how-to-recruit-candidates-with-published-journals-and-patents/","content":"If there’s anything that the pandemic reminded us, it’s that...","read_time":"2 min","classify":["Product"]},
    {"title":"Your Ultimate Guide to Sourcing Candidates with Hiretual","img":"https://hiretual.com/wp-content/uploads/2021/05/Website-Blog-Header-1080x675.png","url":"/blog/your-ultimate-guide-to-sourcing-candidates-with-hiretual/","content":"It’s a bird! It’s a plane! Nope, it’s you – a soon-to-be AI Sourcing...","read_time":"10 min","classify":["Talent Sourcing","Recruiting Strategy","Recruitment Operations","Product"]},
    {"title":"The 5-Step Guide to Boost Candidate Engagement with Hiretual","img":"https://hiretual.com/wp-content/uploads/2019/05/Website-Blog-Header-11-1080x675.png","url":"/blog/boost-candidate-engagement-with-hiretual","content":"When it comes to recruiting, successful candidate engagement is...","read_time":"7 min","classify":["Candidate Engagement","Recruiting Strategy"]},
    {"title":"How to Build A Collaborative Recruiting Team","img":"https://hiretual.com/wp-content/uploads/2021/03/Jonathan-Kidder-Guest-Blog-Header-1080x675.png","url":"/blog/build-collaborative-recruiting-team/","content":"The concept of building a strong team is nothing new. A quick glance...","read_time":"3 min","classify":["Team Collaboration"]},
    {"title":"Boolean Search Recruiting With Hiretual: Everything You Need To Know","img":"https://hiretual.com/wp-content/uploads/2021/04/9-1080x675.png","url":"/blog/boolean-recruiting-tools-with-hiretual/","content":"Boolean search recruiting has been a staple in the industry for a long ...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"3 Ways To Optimize Team Collaboration with Hiretual","img":"https://hiretual.com/wp-content/uploads/2021/04/OptimizeTeamCollab-BlogHeader-1080x675.png","url":"/blog/make-team-collaboration-easy-with-hiretual/","content":"You’ve probably heard the saying, “teamwork makes the dream work.” ...","read_time":"3 min","classify":["Team Collaboration"]},
    {"title":"How To Create An Email Sequence That Converts Passive Talent Into Candidates","img":"https://hiretual.com/wp-content/uploads/2021/04/8-1080x675.png","url":"/blog/create-email-sequence-for-recruiting-outreach/","content":"16%. 28%. 36%. 41%. Confused? According to Lever’s 2019 Talent Benchmar...","read_time":"5 min","classify":["Candidate Engagement"]},
    {"title":"4 Ways to Increase Your Email Response Rates","img":"https://hiretual.com/wp-content/uploads/2021/04/blog_header_responserates-1080x675.png","url":"/blog/increase-email-response-rate/","content":"Did you know that since the pandemic started, we got an additional 40.6...","read_time":"3 min","classify":["Candidate Engagement"]},
    {"title":"How to Stand Out in a Busy Inbox: Recruiting Email Templates And Tips","img":"https://hiretual.com/wp-content/uploads/2021/04/7-1080x675.png","url":"/blog/recruiting-email-templates/","content":"We all know that almost everyone is one social media @ or DM away. But ...","read_time":"6 min","classify":["Candidate Engagement"]},
    {"title":"4 Essential Tips for Writing a Personalized Recruitment Email","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.28.25-AM-1080x675.png","url":"/blog/personalized-recruitment-cold-email-tips/","content":"The average person today is bombarded with information from multiple...","read_time":"2 min","classify":["Candidate Engagement"]},
    {"title":"Best Candidates Email-Finder for Recruiters","img":"https://hiretual.com/wp-content/uploads/2020/07/Website-Blog-Header-3-1080x675.png","url":"/blog/best-email-finding-tool-for-recruiter/","content":"If there’s one way to throw a wet blanket over effective networking in ...","read_time":"4 min","classify":["Candidate Engagement"]},
    {"title":"4 Reasons Why Your InMail Isn’t Working Its Magic","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-24-at-11.13.08-AM-1080x675.png","url":"/blog/four-reasons-why-your-inmail-isnt-working-its-magic/","content":"With so many recruiters relying on LinkedIn in a tight labor market, it...","read_time":"3 min","classify":["Candidate Engagement"]},
    {"title":"Optimize Candidate Experience Using Metric Data","img":"https://hiretual.com/wp-content/uploads/2021/04/blog_header_jkidder_metrics-1080x675.png","url":"/blog/optimize-candidate-experience-using-metric-data/","content":"The term “candidate experience” is nothing new in the recruiting indust...","read_time":"3 min","classify":["Data & Metrics"]},
    {"title":"Introducing Hiretual Talent Data Cloud","img":"https://hiretual.com/wp-content/uploads/2020/05/Talent-Fusion-Social-1590x995-1-1080x675.png","url":"/blog/update-hiretual-talent-data-cloud/","content":"We hear the term ‘data-driven’ often. But what does it really mean to p...","read_time":"4 min","classify":["Data & Metrics"]},
    {"title":"4 Benefits of Data-Driven Recruitment with Hiretual Market Insights","img":"https://hiretual.com/wp-content/uploads/2021/04/blog_header_datadriven-1080x675.png","url":"/blog/benefits-of-data-driven-recruitment-with-hiretual/","content":"Imagine you’re on vacation and planning a night out with your friends. ...","read_time":"4 min","classify":["Data & Metrics"]},
    {"title":"Product of the Year | Hiretual","img":"https://hiretual.com/wp-content/uploads/2019/08/02-3-1080x675.png","url":"/blog/big-awards-2018-product-of-the-year-for-recruiting-and-hr-hiretual/","content":"Mountain View, CA —October 3, 2018— Hiretual was named 2018 Product of ...","read_time":"1min","classify":["Events"]},
    {"title":"Let’s Talk Healthcare Recruitment at OSWAHCR Education Day!","img":"https://hiretual.com/wp-content/uploads/2019/11/Hiretual-@-OSWAHCR-1080x675.png","url":"/blog/hiretual-attending-oswahcr-education-day-2019/","content":"We’re attending the Oregon and Southwest Washington Associate for...","read_time":"1 min","classify":["Events"]},
    {"title":"Conference Season Recap!","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-28-at-4.22.18-PM-1080x675.png","url":"/blog/conference-season-recap-from-hiretual/","content":"The Hiretual team had such a wonderful time meeting so many HR and tale...","read_time":"2 min","classify":["Events"]},
    {"title":"Hiretual is headed to the ERE Recruiting Conference!","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.22.45-AM-1080x675.png","url":"/blog/hiretual-attending-ere-recruiting-conference-2019/","content":"SourceCon and HR Tech are over, but we’re not done meeting more of you ...","read_time":"1 min","classify":["Events"]},
    {"title":"Introducing A New Season of Coffee with Hiretual","img":"https://hiretual.com/wp-content/uploads/2020/10/Website-Blog-Header-9-1080x675.png","url":"/blog/seaeson-2-coffee-with-hiretual/","content":"If you’re like the Hiretual team, then you know how important team coff...","read_time":"2 min","classify":["Events"]},
    {"title":"Skills Recruiters Learned During The Pandemic","img":"https://hiretual.com/wp-content/uploads/2020/11/Skills-Recruiters-Learned-Blog-Header-1080x675.png","url":"/blog/skills-recruiters-learned-during-pandemic/","content":"As we reflect on the pandemic, words like chaotic, depressing, and exha...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual Wins 2021 BIG Innovation Award for Hiretual Talent Data Cloud’s AI-powered ATS Integrations","img":"https://hiretual.com/wp-content/uploads/2021/01/BIG-Innovation-Award-Blog-Header-1-1024x640-1.png","url":"/blog/hiretual-wins-2021-big-innovation-award/","content":"Hiretual Wins 2021 BIG Innovation Award for Hiretual...","read_time":"1 min","classify":["Product"]},
    {"title":"Reach Out to Candidates on Behalf of Hiring Managers","img":"https://hiretual.com/wp-content/uploads/2019/09/Screen-Shot-2019-10-17-at-9.54.27-AM-1080x675.png","url":"/blog/update-email-delegation/","content":"It’s a candidate-driven market and recruiters are always striving to wi...","read_time":"1 min","classify":["Product"]},
    {"title":"September Product Updates: Optimize Your Search with Diversity Insights and Filters, Boolean and Twitter Support, and More","img":"https://hiretual.com/wp-content/uploads/2020/09/Website-Blog-Header-8-1080x675.png","url":"/blog/update-product-diversity-candidates-filter-and-more/","content":"The job market today is flooded with talented individuals. Hiretual...","read_time":"2 min","classify":["Product","Diversity & Inclusion"]},
    {"title":"Hiretual’s Advanced Resume Parsing Beats Popular Tools In Accuracy Tests","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.52.28-AM-1080x675.png","url":"/blog/hiretuals-advanced-resume-parsing-beats-popular-tools-in-accuracy-tests/","content":"Resume parsing can be defined as using technology to extract meaningful...","read_time":"1 min","classify":["Product"]},
    {"title":"SOC 2 Type II Certification","img":"https://hiretual.com/wp-content/uploads/2019/08/Screen-Shot-2019-08-21-at-4.16.17-PM-1080x675.png","url":"/blog/soc-2-type-ii-certification-achieved-by-hiretual/","content":"Hello friends of Hiretual,We are proud to announce that Hiretual has...","read_time":"1 min","classify":["Product"]},
    {"title":"TecHR Series: HR Tech and AI","img":"https://hiretual.com/wp-content/uploads/2019/02/techr-1080x675.png","url":"/blog/techr-hr-technology-and-ai/","content":"From the media company behind AiThority comes a brand new sister site f...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual Pricing 101: Explore The Right Plan For You","img":"https://hiretual.com/wp-content/uploads/2020/09/Screen-Shot-2020-09-15-at-4.40.39-PM-1080x675.png","url":"/blog/hiretual-pricing-find-your-right-plan/","content":"Experience simple and actionable recruitment without breaking the bank....","read_time":"2 min","classify":["Product","Diversity & Inclusion"]},
    {"title":"What is Hiretual?","img":"https://hiretual.com/wp-content/uploads/2019/06/desk-3139127_1920.jpg","url":"/blog/what-is-hiretual/","content":"Hiretual is every recruiter’s best friendWe’re the #1 AI-powered recrui...","read_time":"4 min","classify":["Product","Diversity & Inclusion"]},
    {"title":"Hiretual Has New Two-Way ATS Integrations for Crelate and Recruitee","img":"https://hiretual.com/wp-content/uploads/2019/08/city.png","url":"/blog/crelate-and-recruitee-two-way-ats-integration/","content":"We have expanded our line of two-way integrations with two new addition...","read_time":"1 min","classify":["Product"]},
    {"title":"Zoho Recruit and Hiretual Integration","img":"https://hiretual.com/wp-content/uploads/2019/08/zoho-1080x578.png","url":"/blog/zoho-recruit-and-hiretual-integration/","content":"We’re thrilled to announce the launch of our latest active integration ...","read_time":"1 min","classify":["Product"]},
    {"title":"Breezy HR and Hiretual Two-Way Integration is Live","img":"https://hiretual.com/wp-content/uploads/2019/08/breezy-logo-1080x675.png","url":"/blog/breezy-hr-and-hiretual-two-way-integration/","content":"Our family of integrations is growing so fast!We’re excited to announce...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual and Beamery Announce Partnership to Boost Talent Search and Engagement","img":"https://hiretual.com/wp-content/uploads/2019/10/news-beamery-hiretual.jpg","url":"/blog/beamery-and-hiretual-partnership-to-boost-talent-search-and-engagement/","content":"Hiretual is excited to announce that we have partnered with Beamery to...","read_time":"1 min","classify":["Product"]},
    {"title":"Okta and Hiretual Integration","img":"https://hiretual.com/wp-content/uploads/2019/10/OKTA-Hiretual-1080x628.png","url":"/blog/okta-and-hiretual-integration/","content":"We’re excited to announce that Okta is now a part of Hiretual’s family ...","read_time":"1 min","classify":["Product"]},
    // {"title":"What can I do if Hiretual Chrome Extension is not working","img":"https://downloads.intercomcdn.com/i/o/61272397/0ec1ac42fd21f853e002ddd2/Screen+Shot+2018-05-29+at+1.13.03+PM.png","url":"/blog/what-can-i-do-if-hiretual-chrome-extension-is-not-working/","content":"Please first go to the chrome extension management : chrome://extension...","read_time":"1 min","classify":["Product"]},
    {"title":"AI Recruitment Software, Hiretual, Closes Off Another Year of Extensive Product Growth With New Sourcing Features and Integrations","img":"https://hiretual.com/wp-content/uploads/2021/01/Hiretuality-Press-Release-Image-1080x675.png","url":"/blog/scholar-sourcing-and-gsuite-integrations/","content":"AI Recruitment Software, Hiretual, Closes Off Another Year of Extensive...","read_time":"2 min","classify":["Product"]},
    {"title":"Is Hiretual Enterprise Right For You? Benefits & Features","img":"https://hiretual.com/wp-content/uploads/2020/03/Website-Blog-Header-1080x675.png","url":"/blog/hiretual-enterprise-benefits-and-features/","content":"Table of contents: Why Hiretual Enterprise?Who Does Hiretual Enterprise...","read_time":"5 min","classify":["Product","Diversity & Inclusion"]},
    {"title":"Press Release: Hiretual Announces Partnership with Evry1","img":"https://hiretual.com/wp-content/uploads/2021/04/Website-Blog-Header-1080x675.png","url":"/blog/hiretual-announces-every1-partnership/","content":"Read the full press release here The new online community offers free r...","read_time":"1 min","classify":["Product"]},
    {"title":"American Business Awards Winner","img":"https://hiretual.com/wp-content/uploads/2019/08/stevie-silver-1080x675.png","url":"/blog/2019-american-business-awards-silver-winner/","content":"We’re delighted to announce today that Hiretual is a Silver winner in t...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual Wins Two Silver Stevies","img":"https://hiretual.com/wp-content/uploads/2019/08/Screen-Shot-2019-10-17-at-10.23.59-AM-1080x675.png","url":"/blog/stevie-international-business-awards-two-silver-stevies/","content":"Hiretual took home two Silver Stevie medals at the 16th Annual Stevie ...","read_time":"2 min","classify":["Product"]},
    {"title":"Recruiting Automation: Hiretual Ranks 1 on 2019 G2 Crowd","img":"https://hiretual.com/wp-content/uploads/2019/08/G2-Crowd.jpg","url":"/blog/g2-crowd-2019-recruiting-automation-software-champion/","content":"Great news! Hiretual is ranked number one in Top 12 Easiest to Use Recr...","read_time":"1 min","classify":["Product"]},
    {"title":"November Product Updates: Bulk Upload Enhancement, Google Search Results Enhancement, and More","img":"https://hiretual.com/wp-content/uploads/2020/11/November-Product-Update-Blog-Header-1080x675.png","url":"/blog/november-product-updates","content":"With Thanksgiving passing last week, we want to thank our users by cont...","read_time":"2 min","classify":["Product"]},
    {"title":"iCIMS Integrate with Hiretual","img":"https://hiretual.com/wp-content/uploads/2019/08/icims-1080x675.png","url":"/blog/icims-and-hiretual-integration/","content":"Hiretual has added iCIMS, a leading recruiting and applicant tracking s...","read_time":"1 min","classify":["Product"]},
    {"title":"October Product Updates: Upload And View Files With Candidate Files Hub, Increased Boolean Support, And More","img":"https://hiretual.com/wp-content/uploads/2020/11/6-1080x675.png","url":"/blog/october-product-update","content":"While once simple tasks, such as safely going for a walk, have become ...","read_time":"2 min","classify":["Product"]},
    {"title":"January Product Updates: Innovations That Will Change The Industry","img":"https://hiretual.com/wp-content/uploads/2021/01/January-Product-Update-Blog-Header-1-1080x675.png","url":"/blog/january-product-updates/","content":"Over the past two decades, there have been a handful of innovations ...","read_time":"2 min","classify":["Product"]},
    {"title":"Introducing Hiretual’s Brand New Website!","img":"https://hiretual.com/wp-content/uploads/2019/09/Untitled-design-3-1080x675.png","url":"/blog/introducing-hiretual-brand-new-web-design/","content":"Our new and improved look goes hand-in-hand in celebrating how Hiretual...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual has a new look!","img":"https://hiretual.com/wp-content/uploads/2020/08/Website-Blog-Header-5-1080x675.png","url":"/blog/hiretual-sourcing-tool-new-layout/","content":"From sourcing more candidates and searching your ATS to scheduling emai...","read_time":"2 min","classify":["Product"]},
    {"title":"TrustRadius Product Comparison: Hiretual vs Entelo","img":"https://hiretual.com/wp-content/uploads/2019/09/Screen-Shot-2019-10-17-at-9.55.06-AM-1080x675.png","url":"/blog/trustradius-product-comparison-hiretual-vs-entelo/","content":"Find out what TrustRadius users have to say about Hiretual and Entelo’s...","read_time":"1 min","classify":["Product"]},
    {"title":"Hiretual API To Streamline Your Recruiting Workflow","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.53.51-AM-1080x675.png","url":"/blog/api-launch-to-streamline-your-recruiting-workflow/","content":"The Hiretual API will allow you to sync projects, candidates, and your ...","read_time":"1 min","classify":["Product"]},
    {"title":"AI Natural Language Processing in Recruiting","img":"https://hiretual.com/wp-content/uploads/2019/01/banner.png","url":"/blog/ai-natural-language-processing-in-recruiting/","content":"Everyone is talking about artificial intelligence and the benefits AI o...","read_time":"1 min","classify":["Product"]},
    {"title":"How Should You Use Hiretual’s Chrome Extension?","img":"https://hiretual.com/wp-content/uploads/2019/06/Google-Chrome-Blog-Updated-Header-1080x675.png","url":"/blog/how-to-use-hiretual-chrome-extension/","content":"As a recruiter’s best friend, we want you to have the best recruiting t...","read_time":"2 min","classify":["Product","Recruitment Operations"]},
    {"title":"Spooky Special: 6 Recruiter Horror Stories","img":"https://hiretual.com/wp-content/uploads/2020/11/2-1080x675.png","url":"/blog/recruiter-horror-stories","content":"With the incoming chill of Fall, the sun setting sooner each day, and H...","read_time":"2 min","classify":["Recruiter Stories"]},
    {"title":"Things Recruiters Are Thankful For This Thanksgiving","img":"https://hiretual.com/wp-content/uploads/2020/11/revised-Thanksgiving-Blog-Header-1080x675.png","url":"/blog/recruiters-thankful-thanksgiving","content":"Although Thanksgiving is approaching soon, it may feel like there are ...","read_time":"2 min","classify":["Recruiter Stories"]},
    {"title":"The Importance of Mental Health for Hiretual and Employees Everywhere","img":"https://hiretual.com/wp-content/uploads/2020/11/mental-health-image-1080x675.png","url":"/blog/mental-health-for-hiretual/","content":"As strange as it may sound, our company’s mission is to make people ...","read_time":"2 min","classify":["Recruiter Stories"]},
    {"title":"Didn’t Attend Hiretuality? Here Are 5 Recruitment Hacks You Missed Out On","img":"https://hiretual.com/wp-content/uploads/2021/01/Hiretuality-Recap-Final-Blog-Header-1080x675.png","url":"/blog/hiretuality-5-recruitment-hacks/","content":"In 2020, it felt like we barely used the word “win.” But the good news ...","read_time":"4 min","classify":["Recruiting Strategy"]},
    {"title":"The Overreliance on LinkedIn: What You Can Do About It","img":"https://hiretual.com/wp-content/uploads/2020/05/Website-Blog-Header-3-1-1080x675.png","url":"/blog/guest-posting-is-linkedin-effective-for-recruiting/","content":"As recruiters, we tend to stick with a standard procedure for finding ...","read_time":"5 min","classify":["Recruiting Strategy"]},
    {"title":"How To Manage An Emotional Job Market In 2020","img":"https://hiretual.com/wp-content/uploads/2020/07/Marc-Bond-Blog-Header-Image-1080x675.png","url":"/blog/guest-posting-how-to-manage-an-emotional-job-market-in-2020/","content":"Coming out of the COVID-19 pandemic, there is going to be huge change ...","read_time":"5 min","classify":["Recruiting Strategy"]},
    {"title":"A Guide To Build Technical Teams","img":"https://hiretual.com/wp-content/uploads/2020/06/Website-Blog-Header-3-1080x675.png","url":"/blog/guest-posting-a-guide-to-build-technical-team/","content":"When it comes to building technical teams – teams that include technica...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"The 5Ws Of Being A Healthcare Recruiter","img":"https://hiretual.com/wp-content/uploads/2019/11/2-1080x675.png","url":"/blog/five-w-of-a-healthcare-recruiter/","content":"Healthcare recruitment poses substantial differences from other forms ...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"What Does Being Intentional Look Like For A Recruiter?","img":"https://hiretual.com/wp-content/uploads/2020/04/Website-Blog-Header-1080x675.png","url":"/blog/guess-posting-what-does-being-intentional-look-like-for-a-recruiter/","content":"Essentially the definition of “being intentional” is doing something ...","read_time":"4 min","classify":["Recruiting Strategy"]},
    {"title":"Recap: Hiretual Partner Summit 2020","img":"https://hiretual.com/wp-content/uploads/2020/08/Recap-Blog-Header-1-1080x675.png","url":"/blog/partner-summit-2020-recap-from-hiretual/","content":"Over the past several months, the Hiretual team has been working to ...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"Reinventing the Traditional Resume","img":"https://hiretual.com/wp-content/uploads/2020/01/Screen-Shot-2020-01-27-at-10.08.06-AM-1080x675.png","url":"/blog/is-traditional-resume-still-a-thing/","content":"With the rise in social networking, digital professional platforms, and...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"Cut Your Losses: How AI Can Help Your Recruiting","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.28.02-AM-1080x675.png","url":"/blog/how-ai-can-help-your-recruiting/","content":"In today’s tech-centered employment market, the demand for software dev...","read_time":"2 min","classify":["Recruiting Strategy"]},
    {"title":"3 Tips To Hire With Limited Resources","img":"https://hiretual.com/wp-content/uploads/2020/09/Website-Blog-Header-5-1080x675.png","url":"/blog/three-tips-to-hire-with-limited-resources/","content":"If there are recruiting challenges that many of us are familiar with, ...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"Anatomy of an Effective Job Posting Strategy","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-17-at-9.23.23-AM-1080x675.png","url":"/blog/effective-job-posting-strategy/","content":"The “post and pray” strategy is shaky ground for your job posting strat...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"4 Things Every Recruiter Should Know","img":"https://hiretual.com/wp-content/uploads/2021/04/Blog-Header-4-Things-Talent-Leaders...-1080x675.png","url":"/blog/things-recruiter-should-know/","content":"“This is a very noble profession. Always remember how many people you ...","read_time":"6 min","classify":["Recruiting Strategy","Diversity & Inclusion"]},
    {"title":"Healthcare Recruiting During A Pandemic: What Should You Do?","img":"https://hiretual.com/wp-content/uploads/2020/04/Website-Blog-Header-copy-1080x675.png","url":"/blog/healthcare-recruiting-during-covid-what-should-you-do/","content":"Hospitals and medical facilities across the world are facing a big ques...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"Hiretual’s In-House Recruiter Series: Recruiter Pain Points","img":"https://hiretual.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-12-at-5.15.14-PM-1080x675.png","url":"/blog/recruiter-pain-points-by-hiretual-in-house/","content":"Michael Deeb started his career as a Talent Qualification Specialist in...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"How Can Machines Aid Employee Retention?","img":"https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-30-at-11.18.08-AM-1080x675.png","url":"/blog/how-machines-learning-aid-employee-retention/","content":"An employee’s resignation impacts companies greatly, dwindling both ...","read_time":"2 min","classify":["Recruiting Strategy"]},
    {"title":"Tips for Creating A Proactive Talent Acquisition Strategy","img":"https://hiretual.com/wp-content/uploads/2019/08/pexels-photo-2422294-2-1080x675.jpg","url":"/blog/tips-for-creating-a-proactive-talent-acquisition-strategy/","content":"“A proactive talent acquisition strategy that gets ahead of future tale...","read_time":"2 min","classify":["Recruiting Strategy"]},
    {"title":"Hiretual’s In-House Recruiter Series: Technical Recruiting Tips and Strategies","img":"https://hiretual.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-12-at-5.15.14-PM-1080x675.png","url":"/blog/technical-recruiter-tips-and-tricks-by-hiretual-in-house/","content":"It’s no surprise that the recruiting for tech talent is at an all-time ...","read_time":"4 min","classify":["Recruiting Strategy"]},
    {"title":"How Artificial Intelligence Will Power the Future of Recruiting","img":"https://hiretual.com/wp-content/uploads/2019/08/business-people-1080x675.jpg","url":"/blog/how-artificial-intelligence-will-power-the-future-of-recruiting/","content":"“AI is no longer a futuristic topic – it is becoming the greatest trans...","read_time":"3 min","classify":["Recruiting Strategy"]},
    {"title":"Recruiting Trends in 2020 and Beyond: The Industry Breakdown","img":"https://hiretual.com/wp-content/uploads/2020/01/Screen-Shot-2020-01-10-at-3.46.15-PM-1-1080x675.png","url":"/blog/how-recruiting-industry-in-2020-look-like/","content":"What does the state of 2020 recruitment look like? Recruiting isn’t a ...","read_time":"4 min","classify":["Recruiting Strategy"]},
    {"title":"[WEBINAR RECAP] Tackling and Overcoming COVID-19: What Can Recruiters Do?","img":"https://hiretual.com/wp-content/uploads/2020/05/Website-Blog-Header-1-1-1080x675.png","url":"/blog/what-can-recruiter-do-to-overcome-covid-webinar-recap/","content":"If you couldn’t join us last week for our webinar, “Tackling and Overco...","read_time":"5 min","classify":["Recruiting Strategy","Events"]},
    {"title":"Recap: #HIRETUALITY The Future of AI Recruiting","img":"https://hiretual.com/wp-content/uploads/2020/01/Screen-Shot-2020-01-20-at-3.22.52-PM-1080x675.png","url":"/blog/hiretuality-recap-the-future-of-ai-recruiting/","content":"The Hiretual team has worked with over 200,000 recruiters and sourcers ...","read_time":"2 min","classify":["Recruiting Strategy","Events"]},
    {"title":"Recap: Talent Engagement Summit 2019","img":"https://hiretual.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-27-at-9.31.38-AM-1080x675.png","url":"/blog/beamery-talent-engagement-summit-2019-recap-from-hiretual/","content":"You know what they say about experience being the best teacher? In the ...","read_time":"2 min","classify":["Recruiting Strategy","Events"]},
    {"title":"What I Learned From OSWAHCR 2019","img":"https://hiretual.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-13-at-1.56.49-PM-1080x675.png","url":"/blog/what-we-learn-from-oswahcr-2019/","content":"At Hiretual, we believe that being proactive and continuously eager to ...","read_time":"1 min","classify":["Recruiting Strategy","Events"]},
    {"title":"Why Businesses Need Recruitment Operations Now More Than Ever","img":"https://hiretual.com/wp-content/uploads/2021/05/Why-Recruitment-Operations-1080x675.png","url":"/blog/why-recruitment-operations/","content":"When the pandemic began, many businesses went into survival mode. Some ...","read_time":"5 min","classify":["Recruitment Operations"]},
    {"title":"How to Hire Software Developers: 4 Ways to use Hiretual’s AI Sourcing","img":"https://hiretual.com/wp-content/uploads/2021/04/blog_header_hiresoftwaredeveloper-1080x675.png","url":"/blog/how-to-hire-software-developer-with-hiretual/","content":"Sourcing or hiring software developers or any IT and tech role in this ...","read_time":"3 min","classify":["Talent Sourcing","Diversity & Inclusion"]},
    {"title":"How to Recruit Healthcare Professionals: 4 Recruiting Strategies","img":"https://hiretual.com/wp-content/uploads/2021/04/3-1080x675.png","url":"/blog/healthcare-recruiting-strategies","content":"Sourcing for medical and pharmaceutical candidates isn’t the same as so...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"How to Hire Out-of-State Candidates","img":"https://hiretual.com/wp-content/uploads/2021/04/6-1080x675.png","url":"/blog/hire-out-of-state-candidates/","content":"It’s common for recruiters to have to expand their search to source and...","read_time":"2 min","classify":["Talent Sourcing"]},
    {"title":"AI Sourcing: Do’s and Don’ts on How to Source Talent","img":"https://hiretual.com/wp-content/uploads/2021/04/blog_header_aisourcing_dos-1080x675.png","url":"/blog/how-to-source-talent/","content":"Employer competition remains one of the biggest concerns for recruiters...","read_time":"4 min","classify":["Talent Sourcing"]},
    {"title":"How to Build A Successful Active Candidate Sourcing Plan","img":"https://hiretual.com/wp-content/uploads/2021/04/5-1080x675.png","url":"/blog/active-candidate-sourcing/","content":"Previously, we talked about sourcing passive candidates and just how ...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"A Quick Guide to Hiretual’s FREE Chrome Extension","img":"https://hiretual.com/wp-content/uploads/2020/10/Website-Blog-Header-10-1080x675.png","url":"/blog/how-to-add-hiretual-chrome-extension/","content":"Whether you’re actively filling a role, or looking to build out long ...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"How to Source Candidates on GitHub with Hiretual","img":"https://hiretual.com/wp-content/uploads/2020/02/Screen-Shot-2020-02-21-at-10.05.54-AM-1080x675.png","url":"/blog/how-to-source-candidates-on-Github","content":"Why use GitHub for technical recruiting? The biggest challenge when sou...","read_time":"5 min","classify":["Talent Sourcing"]},
    {"title":"AI Sourcing vs Boolean Sourcing: Which is Superior?","img":"https://hiretual.com/wp-content/uploads/2019/08/02-4-1080x675.png","url":"/blog/ai-sourcing-vs-boolean-sourcing/","content":"“Investing time or energy into becoming a master at Boolean is a lot ...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"How to Source for Candidates with a Security Clearance","img":"https://hiretual.com/wp-content/uploads/2020/07/Security-Clearance-Blog-1080x675.png","url":"/blog/source-candidates-with-security-clearance/","content":"Despite the COVID-19 pandemic, hiring for cleared jobs remains largely ...","read_time":"4 min","classify":["Talent Sourcing"]},
    {"title":"Tips to Be a Better Technical Recruiter","img":"https://hiretual.com/wp-content/uploads/2019/08/women-computer.jpg","url":"/blog/eight-tips-and-tricks-to-be-a-better-technical-recruiter/","content":"Editor’s note: This post was originally published on October 23, 2018, ...","read_time":"4 min","classify":["Talent Sourcing"]},
    {"title":"Sourcing vs Recruiting – What’s The Difference?","img":"https://hiretual.com/wp-content/uploads/2020/10/Blog-_-LinkedIn-Images-7-1080x675.png","url":"/blog/different-between-sourcing-vs-recruiting/","content":"Historically, recruitment entails the end-to-end process of acquiring ...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"5 Tips For Better Enterprise Sourcing In 2021","img":"https://hiretual.com/wp-content/uploads/2020/11/Website-Blog-Header-15-1080x675.png","url":"/blog/enterprise-sourcing-2021/","content":"Enterprise companies worldwide have a well-documented history of ...","read_time":"4 min","classify":["Talent Sourcing"]},
    {"title":"How to Recruit Diverse Candidates | 4 Recruitment Platforms to Try","img":"https://hiretual.com/wp-content/uploads/2019/06/Blog-_-LinkedIn-Images-6-1080x675.png","url":"/blog/four-recruitment-platform-to-recruit-diverse-candidates/","content":"New recruitment platforms are key to a healthy sourcing strategyThe ...","read_time":"3 min","classify":["Talent Sourcing","Diversity & Inclusion"]},
    {"title":"Diversity Hiring: Guide to Successfully Hiring Diverse Employees","img":"https://hiretual.com/wp-content/uploads/2019/07/man-3365368_1920-1080x675.jpg","url":"/blog/guide-to-hire-diverse-workforce/","content":"Sourcing top talent today is already tough. But when diversity and ...","read_time":"5 min","classify":["Talent Sourcing","Diversity & Inclusion"]},
    {"title":"5 Advantages of AI Sourcing in Recruitment","img":"https://hiretual.com/wp-content/uploads/2019/08/5-Advantages-of-AI-Sourcing-Blog-Header-1080x675.png","url":"/blog/five-advantages-of-ai-sourcing-in-recruitment/","content":"Boolean searches were once considered the best way to identify best-fit...","read_time":"4 min","classify":["Talent Sourcing"]},
    {"title":"How to Source and Hire a Winning Sales Team","img":"https://hiretual.com/wp-content/uploads/2021/04/1-1080x675.png","url":"/blog/hire-sales-team/","content":"Although the talent pool for sales roles is immense, it’s still a chall...","read_time":"3 min","classify":["Talent Sourcing"]},
    {"title":"What is an Executive Recruiter?","img":"https://hiretual.com/wp-content/uploads/2020/10/Blog-_-LinkedIn-Images-8-1080x675.png","url":"/blog/what-is-an-executive-recruiter/","content":"Executive recruiters are professionals that specialize in recruiting ...","read_time":"2 min","classify":["Talent Sourcing"]},
    {"title":"How to Recruit and Hire Consultants with Hiretual","img":"https://hiretual.com/wp-content/uploads/2021/04/2-1080x675.png","url":"/blog/tips-to-hire-consultants-online/","content":"The talent acquisition process can be challenging to source and hire ...","read_time":"5 min","classify":["Talent Sourcing","Diversity & Inclusion"]},
    {"title":"4 Steps To Stronger Diversity Hiring with Hiretual","img":"https://hiretual.com/wp-content/uploads/2020/10/Website-Blog-Header-11-1080x675.png","url":"/blog/four-steps-for-stronger-diversity-hiring","content":"In recent years, local and global movements have put extra pressure...","read_time":"2 min","classify":["Talent Sourcing","Data & Metrics","Recruiting Strategy","Diversity & Inclusion"]},
    {"title":"5 Effective Ways to Source Passive Candidates","img":"https://hiretual.com/wp-content/uploads/2019/08/cropped-talent-acquisition-1-1080x675.jpg","url":"/blog/recruit-passive-candidates","content":"What’s one of the biggest challenges in the recruiting industry today? ...","read_time":"4 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"3 Ways to Plan for the Great Rehire of 2021","img":"https://hiretual.com/wp-content/uploads/2021/02/header_image_blog_leverswap-1080x675.png","url":"/blog/2021-great-rehire-plan/","content":"Written by Jacqui Barrett-Poindexter for Hiretual on behalf of Lever...","read_time":"4 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"Improve Your Candidate Sourcing Workflow with Hiretual","img":"https://hiretual.com/wp-content/uploads/2021/03/AI-Sourcing-Workflow-Blog-Header-1080x675.png","url":"/blog/improve-candidate-sourcing-workflow","content":"Noisy households, unstable WiFi, and make-shift workspaces. Over the...","read_time":"3 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"World's First Healthcare and IT/Tech Sourcing For Recruiters","img":"https://hiretual.com/wp-content/uploads/2020/01/Screen-Shot-2020-01-20-at-3.22.52-PM-1080x675.png","url":"/blog/top-healthcare-and-tech-sourcing-tool-for-recruiter/","content":"Hiretual announced the launch of its Healthcare and IT/Tech AI Sourcing...","read_time":"2 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"[Webinar Recap] Sourcing Beyond 2020: Building Global Pipelines For Adaptive Work","img":"https://hiretual.com/wp-content/uploads/2020/11/webinar-recap-blog-1080x675.png","url":"/blog/sourcing-beyond-2020","content":"On Tuesday, we had the pleasure of speaking with James Cleaver, VP ...","read_time":"3 min","classify":["Talent Sourcing","Recruiting Strategy"]},
    {"title":"July Product Updates: Engagement & Collaboration Improvements You Might Have Missed","img":"https://hiretual.com/wp-content/uploads/2020/07/Website-Blog-Header-4-1080x675.png","url":"/blog/update-candidates-reengagement/","content":"If you’re a recruiter who values the tagging system, organized sourcing...","read_time":"2 min","classify":["Team Collaboration"]},
    {"title":"How Recruitment Metrics Improve Recruiter-Hiring Manager Relationships","img":"https://hiretual.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-19-at-3.55.20-PM-1080x675.png","url":"/blog/how-recruitment-metrics-improve-recruiter-hiring-manager-relationships/","content":"The U.S. unemployment rate fell to a 50-year low this year, and hiring ...","read_time":"3 min","classify":["Data & Metrics"]},
    {"title":"February Product Updates: Work Better Together","img":"https://hiretual.com/wp-content/uploads/2021/02/February-Product-Update-Blog-Header-1080x675.png","url":"/blog/february-product-update/","content":"Whether it’s “buy one get one free” deals, COVID vaccine shots, ...","read_time":"1 min","classify":["Team Collaboration"]},
    {"title":"December Product Updates: Tools That Bring Everyone Together","img":"https://hiretual.com/wp-content/uploads/2020/12/DPU-Header-Blog-1080x675.png","url":"/blog/december-product-updates/","content":"Hiretual’s favorite part of the holidays? New stuff! When we think...","read_time":"2 min","classify":["Team Collaboration","Diversity & Inclusion"]},
    {"title":"How To Set And Achieve Your Recruitment Goals  ","img":"https://hiretual.com/wp-content/uploads/2019/08/05png-1080x675.png","url":"/blog/how-recruiters-set-and-achieve-recruitment-goals/","content":"“You can have all the right tools in the world, but you also need the...","read_time":"3 min","classify":["Team Collaboration","Data & Metrics"]},
    {"title":"How to Manage a Remote Team with Recruiting Reports: Tips for Team Reporting","img":"https://hiretual.com/wp-content/uploads/2020/05/Website-Blog-Header-2-1080x675.png","url":"/blog/update-recruitment-report-and-team-reporting","content":"Organizations across all industries are facing a similar challenge...","read_time":"4 min","classify":["Team Collaboration","Recruiting Strategy"]}
];
pageData.case_data = [
    {
        case_study: 'talent data cloud',
        title: "How Hiretual’s Talent Data Cloud Simplifies Hiring Data Migration and Management",
        url: "/resources/case-studies/digital-consulting-ma/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/07/case-scaled.jpg',
        classify: ['consulting'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/collaboration-icon1-1.svg',
        size:40,
        read_time: 5,
    },
    {
        case_study: 'FI Consulting',
        title: "With Hiretual, It Can Only Take Hours for FI Consulting to Identify Future Leaders",
        url: "/resources/case-studies/fi-consulting-case-study/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/campaign-creators-qCi_MzVODoU-unsplash-1.png',
        classify: ['consulting'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/fi-consulting.png',
        read_time: 5,
    },
    {
        case_study: "Amtec Inc",
        title: "Amtec Inc. Drives Hiring Productivity by Engaging Quality Talent with Hiretual",
        url: "/resources/case-studies/amtec-inc-case-study/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/amtec-1.png',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/amtec.png',
        size:25,
        read_time: 4,
    },
    {
        case_study: 'Apptio',
        title: "Apptio Finds Qualified Candidates During High-Volume Hiring with Hiretual AI Sourcing",
        url: "/resources/case-studies/apptio-case-study/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/04/apptio-casestudy-top2.png',
        classify: ['tech'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/Apptio_logo.png',
        size:38,
        read_time: 3,
    },
    {
        case_study: "Arkansas Children's Hospital",
        title: "How Arkansas Children’s Hospital Builds Pipelines for Future Roles With Hiretual",
        url: "/resources/case-studies/arkansas-childrens-hospital-case-study/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/04/national-cancer-institute-BxXgTQEw1M4-unsplash-1.png',
        classify: ['healthcare'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/ark-logo.png',
        read_time: 5,
    },
    {
        case_study: 'Bayview',
        title: "Bayview Talent Group Meets High Candidate Demand with Hiretual",
        url: "/resources/case-studies/bayview-case-study-2/",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/04/bayview-casestudy-top.png',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/bayview-logo.png',
        size:13,
        read_time: 3,
    },
    {
        case_study: 'Chenega Corporation',
        title: "Hiretual Elevates  Candidate Engagement for Chenega Corporation",
        url: "/resources/case-studies/chenega-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Chenega-Corporation-Case-Study2-1.png',
        classify: ['government', 'tech'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/chenega-LOGO-300x81-1.png',
        read_time: 3,
    },
    {
        case_study: 'CMK Resources',
        title: "CMK Resources Ramp Up Candidate Engagement With Hiretual",
        url: "/resources/case-studies/cmk-resources-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/bg-1.png',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/Stacked.png',
        size:50,
        read_time: 3,
    },
    {
        case_study: 'Cornerstone',
        title: "Strategic Candidate Sourcing and Elevated Engagement for Cornerstone",
        url: "/resources/case-studies/cornerstone-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Cornerstone.png',
        classify: ['tech', 'staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/logo-cornerstone.png',
        size:57,
        read_time: 3,
    },
    {
        case_study: 'DadJ',
        title: "DADJ Inc. Builds a Successful Recruitment Process in a Tight Labor Market ",
        url: "/resources/case-studies/dadj-case-study-3/",
        img: 'https://hiretual.com/wp-content/uploads/2019/09/DADJ-Case-Study-2.png',
        classify: ['healthcare', 'staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/dadj-logo.png',
        size:32,
        read_time: 3,
    },
    {
        case_study: 'Data Hire',
        title: "Data Hire Reaches Recruiting Objectives with Hiretual AI",
        url: "/resources/case-studies/data-hire-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/bg.png',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/D-H-logo-1.png',
        size:45,
        read_time: 1,
    },
    {
        case_study: 'Dynamic Search Group',
        title: "Dynamic Search Group Sources Fresh Talent from Hiretual’s Industry-Leading Talent Pool",
        url: "/resources/case-studies/dynamic-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2020/01/dynamic-page-bg.jpg',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/dynamic-logo-1.png',
        size:53,
        read_time: 1,
    },
    {
        case_study: 'First Entertainment Credit Union',
        title: "Time-Saving Sourcing and Expanded Talent Pools for First Entertainment Credit Union",
        url: "/resources/case-studies/first-entertainment-credit-union-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/First-Entertainment.png',
        classify: ['banking'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/entertainment-logo-1.png',
        size:43,
        read_time: 3,
    },
    {
        case_study: 'JANE',
        title: "JANE Achieves Higher Candidate Responses with Hiretual Email Sequences",
        url: "/resources/case-studies/jane-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/11/jane-bg.jpg',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/jane-logo.png',
        size:31,
        read_time: 2,
    },
    {
        case_study: 'Poshmark',
        title: "How Poshmark Stands Out During Candidate Sourcing and Engagement with Hiretual",
        url: "/resources/case-studies/poshmark-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2020/06/posh-casestudy-bg.png',
        classify: ['commerce'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/poshmark.png',
        size:26,
        read_time: 3,
    },
    {
        case_study: 'Premier Search',
        title: "Premier Search Inc. Uncovers Candidate Pools with Hiretual",
        url: "/resources/case-studies/premier-search-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/11/premier-top-bg.jpg',
        classify: ['staffing'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/premier-top-1.png',
        size:22,
        read_time: 2,
    },
    {
        case_study: 'Session M',
        title: "Session M Went Beyond Their Professional Network to Find Interested Candidates with Hiretual",
        url: "/resources/case-studies/sessionm-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/header.png',
        classify: ['tech'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/sessionm-logo.png',
        size:85,
        read_time: 2,
    },
    {
        case_study: 'Tango Card',
        title: "Tango Card Attracts Passive Candidates with Data-Driven Insights from Hiretual",
        url: "/resources/case-studies/tango-card-case-study/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/tango-1.png',
        classify: ['tech'],
        logo:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/Logo-tango.svg',
        size:36,
        read_time: 4,
    },

];
pageData.webinar_data = [
    {
        title: "Think Like a Marketer: Setting Recruitment up for Demand Generation",
        content:"Talent acquisition teams today wear multiple hats. They’re business consultants, sales representatives and data analysts. But at all times, talent acquisition teams are extremely good marketers who know how to attract, engage and delight their audience.",
        url: "https://explore.hiretual.com/think-like-a-marketer",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/web.png',
        meeting_time:"Thursday May 13, 2021 | 10 AM PST | 1 PM EST",
    },
    {
        title: "Why Your Candidates Aren’t Listening To You",
        content:"Building the perfect candidate experience is never easy, but the pressure’s on in 2021. We don’t want to make the same mistakes that slowed us down in 2020.",
        url: "https://explore.hiretual.com/improve-candidate-experience",
        img: 'https://hiretual.com/wp-content/uploads/2021/02/Why-Your-Recruiters-Arent-Listening-To-You-Webinar-Design.png',
        meeting_time:"Feb 16, 2021 at 10:00 AM PST",
        recommend:true,
    },
    {
        
        title: "2021 Product Innovation Launch",
        content:"It doesn’t matter where you are or what roles you source for. Join us at Hiretuality 2021 to see how industry leaders are using recruitment technology in the coming year. Plus, be the first to watch our product team unveil our most exciting feature launches for this quarter.",
        url: "https://explore.hiretual.com/hiretuality-product-innovation-launch",
        img: 'https://hiretual.com/wp-content/uploads/2021/02/Hiretuality-Webinar-Header.png',
       meeting_time:"Jan 26, 2021 at 9:00 AM PST",
       recommend:true,
    },
    {
 
        title: "Sourcing Beyond 2020",
        content:"Preparing to hire in 2021 will feel a lot different than how it did preparing for 2020. Workforces have gone digital, global and flexible. A new ‘office life’ will become a norm for many, and so will the demand for adaptable talent.",
        url: "https://explore.hiretual.com/sourcing-beyond-2020",
        img: 'https://hiretual.com/wp-content/uploads/2021/02/Sourcing-Beyond-2020-Webinar-Header.png',
        meeting_time:"Nov 17, 2020 at 10:00 AM PST",
       
    },
    {
        title: "SkillHack by Hiretual",
        content:"Calling all Talent Acquisition professionals!  🗣 Are you ready to get your game on and level up? 🕹 Join us at SkillHack to learn from over 10 awesome speakers!",
        url: "https://explore.hiretual.com/skill-hack",
        img: 'https://hiretual.com/wp-content/uploads/2020/09/Skillhack-Social-General-Image-2.png',
        meeting_time:"Sep 29-30, 2020 at 10:00 AM PST",
        recommend:true,
    },
    {
      
        title: "Hiretual AI Demo",
        content:"In this session, we’ll be taking you through the Hiretual platform to cover product use cases for different industries with our sourcing, engagement, market analytics, ATS integrations, diversity and inclusion capabilities, and more.",
        url: "https://explore.hiretual.com/product-demo-webinar",
        img: 'https://hiretual.com/wp-content/uploads/2020/09/Screen-Shot-2020-09-21-at-10.44.53-AM.png',
        meeting_time:"Aug 25, 2020 at 10:00 AM PST",
       
    },
  
    {
        title: "Navigating A Virtual Hiring Landscape",
        content:"How should the roles and responsibilities of Talent Acquisition professionals change in this new normal? Join us for a talk with Monique Davis on upskilling, going digital, and being a hero to candidates who need it.",
        url: "https://explore.hiretual.com/virtual-recruiting",
        img: 'https://hiretual.com/wp-content/uploads/2020/06/NAVIGATING-A-VIRTUAL-HIRING-LANDSCAPE.png',
       meeting_time:"Jun 18, 2020 at 10:30 AM PST",
      
    },
    {
        title: "Building A Mindful Candidate Engagement Strategy",
        content:"We’ve talked about keeping candidates warm during this time, but what’s the best way to do it? Join James Temple and Marc Hamel to discuss how recruiters can be both effective and mindful communicators.",
        url: "https://explore.hiretual.com/candidate-engagement-strategy",
        img: 'https://hiretual.com/wp-content/uploads/2020/06/Webinar-_-Candidate-Engagement-Strategy-2-2.png',
       meeting_time:"May 26, 2020 at 10:00 AM PST",
    
    },
  
    {
       
        title: "Tackling & Overcoming COVID-19:  What Must Recruiters Do?",
        content:"Join our panel of talent acquisition professionals for a conversation on what recruiters can do to come out stronger in a post-COVID world.",
        url: "https://explore.hiretual.com/overcome-covid19",
        img: 'https://hiretual.com/wp-content/uploads/2020/04/COVID-19-Webinar-4_29-2.png',
        meeting_time:"Apr 29, 2020 at 10:00 AM PST",
       
    },
    {
       
        title: "#HIRETUALITY: Hiretual Talent Data Cloud",
        content:"It’s time to spring clean your ATS data 🛁 Join our speakers from Grab, Wish and Better.com to learn how they manage data to build bigger, better pipelines for any market.",
        url: "https://explore.hiretual.com/talent-data-cloud/",
        img: 'https://hiretual.com/wp-content/uploads/2020/04/Hiretuality-SM-Posts.png',
       meeting_time:"Apr 16, 2020 at 10:00 AM PST",
        
    },
    {
        title: "AI Sourcing On Github",
        content:"We have teamed up with Jer Langhans, to give you a faster and easier way to dive into the deeper untapped pool of Githubs technical candidates without spending hours decoding repository’s.",
        url: "https://explore.hiretual.com/tech-sourcing-on-github",
        img: 'https://hiretual.com/wp-content/uploads/2020/03/Github-Webinar-Slides.png',
        meeting_time:"Mar 17, 2020 at 10:00 PM PST",
    },
    {
    
        title: "#HIRETUALITY: The Future of AI Recruiting",
        content:"Watch the unveiling of the first-ever industry-specific Healthcare and Tech AI Sourcing Solutions. You can now source faster for these special talents!",
        url: "https://discover.hiretual.com/hiretuality-the-future-of-ai-recruitment",
        img: 'https://hiretual.com/wp-content/uploads/2020/01/HIRETUALITY.png',
        meeting_time:"Jan 15, 2020 at 10:00 AM PST",
    },
  
    {
        title: "The 3 Greatest Challenges with Diversity Recruiting",
        content:"Join Darrell James as he discusses the importance of identifying problems and implementing the right strategies to improve diversity in this free webinar. ",
        url: "https://explore.hiretual.com/challenges-with-diversity-recruiting",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Webinar-ad-nov5.png',
        meeting_time:"Nov 5, 2019 at 10:00 AM PDT",
    },
    {
        title: "Sourcing for Modern Recruiters",
        content:"The Sourcing Alchemist Denys uncovers new ways of sourcing and discovering candidates to stay up to date with the current information age!",
        url: "https://explore.hiretual.com/sourcing-for-recruiters",
        img: 'https://hiretual.com/wp-content/uploads/2019/09/sourcing-modern-1.png',
       meeting_time:"Sep 17, 2019 at 10:00 AM PST",
     
    },
];
pageData.ebook_data = [
    {
        title: "DE&I Hiring Continues to Rise. What Does the Talent Market Look Like?",
        content:"Searches for underrepresented talent have increased by 250% on the Hiretual platform since 2020.",
        url: "https://explore.hiretual.com/dei-report-2021",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/10/dei_img.jpg',
        recommend:true,
    },
    {
        title: "what's the Demand for Talent Acquisition?",
        content:"Recruiting roles are in high-demand across in 2021. In this report, we take a look at the demand, supply and salary of recruiting teams.",
        url: "https://explore.hiretual.com/talent-acquisition-report",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/09/image-15.png',
        recommend:true,
    },
    {
        title: "What does the talent market for Software Engineers look like?",
        content:"We analyzed data from our talent pool and user searches surrounding supply and demand, top locations and skills, average market value and diversity hiring.",
        url: "https://explore.hiretual.com/software-engineer-report-2021",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/09/image-16.png',
        recommend:true,
    },
    {
        title: "Recruiting for Recovery in 2021",
        content:"A report on challenges, trends and solutions that will inform your impact post-pandemic hiring.",
        url: "https://explore.hiretual.com/recruiting-for-recovery",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/07/2021EBOOK.png',
    },

    {
        title: "Anticipate Emerging Diversity Trends and Challenges",
        content:"We surveyed 750 Talent Acquisition professionals to see what can be expected this year when hiring for diversity.",
        url: "https://explore.hiretual.com/hiretual-ebook-diversity-1-pager",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/06/firstimg.png',
    },
    {
        title: "2021 Recruitment Outlook Report",
        content:"Overcome a steep climb in 2021 with Hiretual's exclisive insights on how Talent Acquisition is addressing new digital priorities and challenges.",
        url: "https://explore.hiretual.com/2021-recruitment-trends",
        img: 'https://hiretual.com/wp-content/uploads/2021/01/2021-recruitment-trends-image-ebook-.png',
        
    },
    {
        title: "4 Ways Technology is Transforming Diversity and Recruiting",
        content:"Artificial Intelligence. Machine Learning. Natural Language Processing. These are just some of the technology that are empowering employers to make better, inclusive decisions.",
        url: "https://explore.hiretual.com/technology-transforming-diversity",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/07/Flat_iPad.png',
    },
    {
        title: "Managing Bias in the Recruitment Process",
        content:"To succeed in attracting and retaining a diverse and inclusive workforce, recruiters must first work to identify and manage bias as a team.",
        url: "https://explore.hiretual.com/managing-bias-in-recruiting",
        img: 'https://hiretual.com/wp-content/uploads/2021/01/managing-bias-ebook-image-2.png',
    },
    {
        title: "The Modern Recruiter's Playbook For The New Normal",
        content:"The role of the recruiter today cannot be upscaled to facilitate a more virtual world unless recruiters do their part in upskilling themselves in using HR technology.",
        url: "https://explore.hiretual.com/modern-recruiters-playbook",
        img: 'https://hiretual.com/wp-content/uploads/2021/01/modern-playbook-680x910-1.png',
    },
    {
        title: "Guide to A Successful Recruiter-Hiring Manager Relationship ",
        content:"Build a strategic partnership with your hiring manager to improve the quality of your recruiting workflow and timeline.",
        url: "https://explore.hiretual.com/hiring-manager-partnership",
        img: 'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/08/cover-1.png',
        
    },
    {
        title: "10 Key Trends Recruiters Need For 2020",
        content:"We’ve gathered 10 recruitment trends for the new decade. With these benchmarks, recruiters and hiring teams can ramp up their 2020 strategies.",
        url: "https://explore.hiretual.com/10-key-trends-for-2020",
        img: 'https://hiretual.com/wp-content/uploads/2021/01/10keys-cover.jpg',
       
    },
    
    {
        title: "Ultimate Guide To Email Personalizatio",
        content:"Effective personalization of sourcing emails should always be rooted in a deep understanding of the targeted groups. Fid out more from the guide.",
        url: "https://explore.hiretual.com/email-personalization",
        img: 'https://hiretual.com/wp-content/uploads/2019/12/email-wp-cover.jpg',
       
    },
    {
        title: "Give Disadvantaged Graduates A Better Future",
        content:"It’s important for recruiters and organizations to cultivate the success of candidates with diverse backgrounds and life experiences. Read more.",
        url: "https://explore.hiretual.com/graduates",
        img: 'https://hiretual.com/wp-content/uploads/2019/11/disadvantaged-cover-1.jpg',
        
    },
    {
        title: "People Retention and Machine Learning",
        content:"Machine Learning can aid organizations in retaining employees by predicting and identifying employee behavior. Find out how it works.",
        url: "https://explore.hiretual.com/whitepaper-people-retention-and-machine-Learning",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-24-at-3.38.34-PM.png',
    
    },
    {
        title: "Navigate the Current Workforce with AI Recruitment Technology",
        content:"AI does not eliminate the demand for recruiters. Rather, it elevates recruiters’ potential to engage with hiring team and qualified candidates. Read more.",
        url: "https://hiretual.com/recruiting-that-makes-sense/",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-02-at-8.58.17-AM.png',
       
    },
    {
        title: "Making a Difference with a Recruiting Roadmap",
        content:"Find out how we partnered with Michael Goldberg to visualizing and building a result-driven plan to transform ineffective recruitment practices.",
        url: "https://explore.hiretual.com/recruiting-roadmap",
        img: 'https://hiretual.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-02-at-9.57.31-AM.png',
      
    },
    {
        title: "The Economy Is Good Is That Bad For Business?",
        content:"How to overcome recruiting problem in a tight labor market, strategies to retain your current employees and more. How economy affecting the business",
        url: "https://explore.hiretual.com/economy-and-business",
        img: 'https://hiretual.com/wp-content/uploads/2019/08/whitepaper2-1.png',
     
    },
    {
      
        title: "Business Impact of AI on Recruiting",
        content:"As talent retention becomes a bigger challenge now than ever, employers are in dire need to keep their workforce engaged. Read more.",
        url: "https://explore.hiretual.com/Business-Impact-of-AI-on-Recruiting",
        img: 'https://hiretual.com/wp-content/uploads/2019/08/whitepaper3.png',
    },
    {
        title: "A Proactive Talent Acquisition Strategy is Critical In A Tight Labor Market",
        content:"The current demand for talent is high and qualified candidates are in short supply. What strategy should we take to retain top talent?",
        url: "https://explore.hiretual.com/talent-acquisition-strategy",
        img: 'https://hiretual.com/wp-content/uploads/2019/08/whitepaper4.png',
    },

];
pageData.coffee_season = 3;
pageData.coffee_data = [
    // s3
    {
        title:'Amplifying Underrepresented Voices in HR',
        videolink:'https://www.youtube.com/embed/B7LSIJHT1do',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/03/coffee3-10.png',
        season:3,
    },
    {
        title:'What Should Candidate Experience Look Like in 2021',
        videolink:'https://www.youtube.com/embed/r_hzTahIT7Y',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/03/coffee3.9.png',
        season:3,
    },
    {
        title:'How Talent Acquisition Drives Business',
        videolink:'https://www.youtube.com/embed/LOC5stvotnU',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/02/coffee3-8.png',
        season:3,
    },
    {
        title:'The Biggest Question Recruiters Need to Answer',
        videolink:'https://www.youtube.com/embed/vpcH9RXGbkM?',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/02/coffee3-7-1.png',
        season:3,
    },
    {
        title:'How Recruiters Can Be An Ally',
        videolink:'https://www.youtube.com/embed/yMtnm0ASzPw',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/02/coffee3-6.png',
        season:3,
    },
    {
        title:'How to Use Recruitment Tech Better in the 2020s',
        videolink:'https://www.youtube.com/embed/Cde8F-U6Ono',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/02/s3_ep5-1.png',
        season:3,
    },
    {
        title:'3 Things Recruiters Should Remember',
        videolink:'https://www.youtube.com/embed/E2h_dYWJqig',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/02/3-Things-Recruiters-Should-Remember.png',
        season:3,
    },
    {
        title:'Why is Talent Acquisition So Important?',
        videolink:'https://www.youtube.com/embed/N01T3E6lR8s',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/01/coffe3-1.png',
        season:3,
    },
    {
        title:'The Recruiting Utopia',
        videolink:'https://www.youtube.com/embed/OtA8UAwIqQg',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/01/coffee_s3_2.png',
        season:3,
    },
    {
        title:'What’s Wrong with Traditional Recruiting?',
        videolink:'https://www.youtube.com/embed/U_f58AU3--k',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2021/01/coffee-s3-1-1.png',
        season:3,
    },
    // s2
    {
        title:'How to Pick the Best Recruitment Technology for 2021',
        videolink:'https://www.youtube.com/embed/khJ08_htH60',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/11/Screen-Shot-2020-11-17-at-6.41.11-PM.png',
        season:2,
    },
    {
        title:'What Do You Need In A Video Interviewing Tool?',
        videolink:'https://www.youtube.com/embed/s0C0IQR9cA4',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/11/2-9.png',
        season:2,
    },
    {
        title:'The Guide to Recruiting Like a Sports Agent',
        videolink:'https://www.youtube.com/embed/U8kx_8B7dTk',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/11/2-8.png',
        season:2,
    },
    {
        title:'How To Recruit Like A Project Manager',
        videolink:'https://www.youtube.com/embed/r51InedBCVE',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-7.png',
        season:2,
    }, 
    {
        title:'Ghosting Candidates and Why It Has To Stop',
        videolink:'https://www.youtube.com/embed/XNKqUvqR970',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/Screen-Shot-2020-10-23-at-1.24.08-PM.png',
        season:2,
    }, 
    {
        title:'Hiretual Employee Exclusive & New Features',
        videolink:'https://www.youtube.com/embed/SRrHvmVFQrw',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-5-1.png',
        season:2,
    }, 
    {
        title:'The Best Practices To Recruiting Diversity & Inclusion',
        videolink:'https://www.youtube.com/embed/5JGIq0ouDi8',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-4-1.png',
        season:2,
    }, 
    {
        title:'Busting the Myths on ‘Unrealistic’ Candidate Experiences',
        videolink:'https://www.youtube.com/embed/O9TQZr0gqiM',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-3-1.png',
        season:2,
    },
    {
        title:'Top Recruiting Trends to End 2020',
        videolink:'https://www.youtube.com/embed/1wlWxPfrpOg',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-2-1.png',
        season:2,
    }, 
    {
        title:'The Recruiters’ Guide to Resumes',
        videolink:'https://www.youtube.com/embed/_QGeEznH_uc',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/2-1-1.png',
        season:2,
    }, 
    // s1
    {
        title:'Creative Business Uses of Hiretual',
        videolink:'https://www.youtube.com/embed/Xefg2eAyB5o',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-10.png',
        season:1,
    }, 
    {
        title:'How To Manage An Emotional Market',
        videolink:'https://www.youtube.com/embed/TIPCWLVrxYc',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-9.png',
        season:1,
    }, 
    {
        title:'How To Find Cleared Talent',
        videolink:'https://www.youtube.com/embed/p8acGNfWFAM',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-8.png',
        season:1,
    }, 
    {
        title:'Using Data to Drive Talent Acquisition',
        videolink:'https://www.youtube.com/embed/NjbFvCBuru0',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-7.png',
        season:1,
    }, 
    {
        title:'A New Era for Inclusive Workforces',
        videolink:'https://www.youtube.com/embed/FhMDFPZ_5Jc',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-6.png',
        season:1,
    }, 
    {
        title:'Recruiter-Hiring Manager Relationships',
        videolink:'https://www.youtube.com/embed/rodsJq2n9cM',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-5.png',
        season:1,
    }, 
    {
        title:'The Candidate-Driven Recruiter',
        videolink:'https://www.youtube.com/embed/yiuDRvD2YYA',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-4.png',
        season:1,
    }, 
    {
        title:'Remote Teams 101',
        videolink:'https://www.youtube.com/embed/9eldfcNRZG0',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-3.png',
        season:1,
    },
    {
        title:'The Intentional Recruiter',
        videolink:'https://www.youtube.com/embed/-thQgEElHqQ',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-2.png',
        season:1,
    },
    {
        title:'‘Batching’ Your Recruiting',
        videolink:'https://www.youtube.com/embed/E2h_dYWJqig',
        img:'https://staging-hiretualcom.kinsta.cloud/wp-content/uploads/2020/10/1-1.png',
        season:1,
    }
   
]
module.exports = pageData;
